- name: prepare_systemd_service
  become: yes
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
  - hadoop-mapreduce-historyserver

- name: reload_systemd_service
  become: yes
  systemd:
    daemon_reload: yes

- name: create_pid_dir
  become: yes
  file: path={{ mapred_pid_dir }} state=directory mode=775 owner=mapred group=mapred
  
- name: create_log_dir
  become: yes
  file: path={{ mapred_log_dir }} state=directory mode=755 owner=mapred group=hadoop

- name: copy_default_file
  become: yes
  template: src=default_{{ item }}.j2 dest=/etc/default/{{ item }} mode=755 owner=root group=root 
  with_items:
  - hadoop-mapreduce-historyserver
