- name: check_datanode_data_dirs
  sudo: yes
  shell: ls {{ item }}/*
  with_items: dfs_datanode_data_dirs
  register: check_datanode_data_dirs
  changed_when: false
  failed_when: false
  always_run: true

- name: delete_datanode_data_dirs
  sudo: yes
  file: path={{ item.item }} state=absent
  with_items: check_datanode_data_dirs.results
  when: item.rc == 0
  
- name: recreate_datanode_data_dirs
  sudo: yes
  file: path={{ item.item }} state=directory mode=755 owner=hdfs group=hadoop
  with_items: check_datanode_data_dirs.results
  when: item.rc == 0
