- name: fix_init_scripts_2.2
  sudo: yes
  template: src=init_{{ item }}_{{ hdp_version }}.j2 dest=/usr/hdp/{{ hdp_version }}/etc/rc.d/init.d/{{ item }} mode=755
  with_items:
  - hadoop-yarn-resourcemanager
  when: hdp_version == '2.2.0.0-2041'
  
- name: fix_init_scripts_2.3later
  sudo: yes
  template: src=init_{{ item }}_{{ hdp_version }}.j2 dest=/usr/hdp/{{ hdp_version }}/hadoop-yarn/etc/rc.d/init.d/{{ item }} mode=755
  with_items:
  - hadoop-yarn-resourcemanager
  when: hdp_version != '2.2.0.0-2041'
  
- name: create_symbolic_link_to/etc/init.d
  sudo: yes
  file: path=/etc/init.d/{{ item }} state=link src=/usr/hdp/{{ hdp_version }}/etc/rc.d/init.d/{{ item }}
  with_items:
  - hadoop-yarn-resourcemanager
  when: hdp_version == '2.2.0.0-2041'
  
- name: create_symbolic_link_to/etc/init.d
  sudo: yes
  file: path=/etc/init.d/{{ item }} state=link src=/usr/hdp/{{ hdp_version }}/hadoop-yarn/etc/rc.d/init.d/{{ item }}
  with_items:
  - hadoop-yarn-resourcemanager
  when: hdp_version != '2.2.0.0-2041'

- name: create_yarn_pid_dir
  sudo: yes
  file: path={{ yarn_pid_dir }} state=directory mode=755 owner=yarn group=yarn
  
- name: create_yarn_log_dir
  sudo: yes
  file: path={{ yarn_log_dir }} state=directory mode=755 owner=yarn group=hadoop

- name: copy_default_file
  sudo: yes
  template: src=default_{{ item }}.j2 dest=/etc/default/{{ item }} mode=755 owner=root group=root 
  with_items:
  - hadoop-yarn-resourcemanager