- name: create_hbase_groups
  become: yes
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
  with_items:
    - { name: hbase, gid: "{{ hbase_gid | default(omit) }}" }
    - { name: hadoop, gid: "{{ hadoop_gid | default(omit) }}" }

- name: create_hbase_user
  become: yes
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.name }}"
    groups:
      - hadoop
  with_items:
    - { name: hbase, uid: "{{ hbase_uid | default(omit) }}" }

- name: prepare_package_dir
  become: yes
  file:
    path: "{{ hbase_dir }}/package"
    state: directory

- name: download_hbase_package
  become: yes
  get_url:
    url: "{{ hbase_release_url }}"
    dest: "{{ hbase_dir }}/package/{{ hbase_package_filename }}.tar.gz"
    checksum: "{{ hbase_release_checksum }}"

- name: extract_hbase_package
  become: yes
  unarchive:
    src: "{{ hbase_dir }}/package/{{ hbase_package_filename }}.tar.gz"
    dest: "{{ hbase_dir }}"
    remote_src: yes

- name: link_latest_package
  become: yes
  file:
    path: "{{ hbase_dir }}/current"
    src: "{{ hbase_dir }}/{{ hbase_package_filename }}"
    state: link

- name: prepare_commands
  become: yes
  template:
    src: "command-wrapper.sh.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: '755'
    owner: root
    group: root
  with_items:
  - hbase
  - hbase-jruby