- name: create_hbase_conf_dir
  sudo: yes
  file: path=/etc/hbase/conf state=directory owner=root group=root mode=755

- include: principal.yml
  sudo: yes
  vars: { kerberos_princ_username: hbase, kerberos_princ_keytab_path: /etc/hbase/conf/hbase.keytab, kerberos_princ_keytab_owner: hbase }
  when: kerberos_realm is defined

- name: copy_jaas_conf
  sudo: yes
  template: src=zk-jaas.conf.j2 dest=/etc/hbase/conf/zk-jaas.conf
  when: kerberos_realm is defined

- name: copy_hbase_conf_files
  sudo: yes
  template: src={{ item }}.j2 dest=/etc/hbase/conf/{{ item }} owner=hbase group=hadoop mode=755
  with_items:
  - hbase-site.xml
  - hbase-env.sh
  - hbase-policy.xml
  - regionservers
  - log4j.properties
  - hadoop-metrics2-hbase.properties
  
- name: copy_hbase_default_file
  sudo: yes
  template: src={{ item }}.j2 dest=/etc/default/{{ item }} owner=hbase group=hadoop mode=755
  with_items:
  - hbase

- name: fix_init_scripts_2.2
  sudo: yes
  template: src=init_{{ item }}_{{ hdp_version }}.j2 dest=/usr/hdp/{{ hdp_version }}/etc/rc.d/init.d/{{ item }} mode=755
  with_items:
  - hbase-master
  when: hdp_version == '2.2.0.0-2041'

# Fix for /etc/init.d/hbase-master: line 61: /usr/hdp/current/hbase-@HBASE_MASTER@/../hbase/conf/hbase-env.sh: No such file or directory
- name: fix_init_scripts_2.3later
  sudo: yes
  template: src=init_{{ item }}_{{ hdp_version }}.j2 dest=/usr/hdp/{{ hdp_version }}/hbase/etc/rc.d/init.d/{{ item }} mode=755
  with_items:
  - hbase-master
  when: hdp_version != '2.2.0.0-2041'
  
- name: create_symbolic_link_to/etc/init.d
  sudo: yes
  file: path=/etc/init.d/{{ item }} state=link src=/usr/hdp/{{ hdp_version }}/etc/rc.d/init.d/{{ item }}
  with_items:
  - hbase-master
  when: hdp_version == '2.2.0.0-2041'
  
- name: create_symbolic_link_to/etc/init.d
  sudo: yes
  file: path=/etc/init.d/{{ item }} state=link src=/usr/hdp/{{ hdp_version }}/hbase/etc/rc.d/init.d/{{ item }}
  with_items:
  - hbase-master
  when: hdp_version != '2.2.0.0-2041'
  
- name: create_hbase_log_dir
  sudo: yes
  file: path={{ hbase_log_dir }} state=directory mode=755 owner=hbase group=hadoop 

- name: deploy_service_test_script
  sudo: yes
  template: src={{ item }}.j2 dest=/usr/local/bin/{{ item }} owner=hbase group=hadoop mode=644
  with_items:
    - hbase-service-test.rb
