- name: check_exists_hfds_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -ls {{ spark_event_log_dir }}
  register: check_exists_hdfs_dir
  changed_when: false
  failed_when: false
  always_run: true
    
- name: create_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -mkdir -p {{ spark_event_log_dir }}
  when: check_exists_hdfs_dir.rc != 0
  
- name: change_owner_and_group_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chown -R spark:spark {{ spark_event_log_dir }}
  when: check_exists_hdfs_dir.rc != 0

- name: change_mode_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chmod -R 1777 {{ spark_event_log_dir }}
  when: check_exists_hdfs_dir.rc != 0
