- name: check_format_state
  become: yes
  stat: path={{ item }}/current
  with_items: "{{ dfs_namenode_name_dirs }}"

- name: FORMAT_namenode
  become: yes
  become_user: hdfs
  shell: hdfs namenode -format -force

- name: FORMAT_ZKFC
  become: yes
  become_user: hdfs
  shell: hdfs zkfc -formatZK -force
  when: hadoop_namenode_servers|length > 1
