- name: create_direcoty_cgroups_scripts
  sudo: yes
  file: path={{ cgroups_scripts_dir }} state=directory owner=root group=root mode=755

- name: copy_cgroups_scripts
  sudo: yes
  template: src={{ item }}.j2 dest={{ cgroups_scripts_dir }}/{{ item }} owner=root group=root mode=755
  with_items:
    - cgroups.sh

- name: copy_cgconfig.conf
  sudo: yes
  template: src=cgconfig.conf.j2 dest=/etc/cgconfig.conf owner=root group=root mode=644

- name: check_chkconfig_cgconfig
  sudo: yes
  shell: chkconfig --list | grep cgconfig | grep on
  ignore_errors: true
  register: check_chkconfig_cgconfig
  changed_when: false
  always_run: true
  
- name: set_on_to_cgconfig_of_chkconfig
  sudo: yes
  shell: chkconfig cgconfig on
  when: check_chkconfig_cgconfig.rc != 0
  
- name: started_cgconfig
  sudo: yes
  service: name=cgconfig state=started

- name: reboot
  sudo: yes
  command: shutdown -r now
  when: result_install_cgroups.changed

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  when: result_install_cgroups.changed

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 127.0.0.1
  when: result_install_cgroups.changed
  
- name: started_cgconfig
  sudo: yes
  service: name=cgconfig state=started
