- name: create_direcoty_cgroups_scripts
  become: yes
  file: path={{ cgroups_scripts_dir }} state=directory owner=root group=root mode=755

- name: copy_cgroups_scripts
  become: yes
  template: src={{ item }}.j2 dest={{ cgroups_scripts_dir }}/{{ item }} owner=root group=root mode=755
  with_items:
    - cgroups.sh

- name: copy_cgconfig.conf
  become: yes
  template: src=cgconfig.conf.j2 dest=/etc/cgconfig.conf owner=root group=root mode=644

- name: reboot
  become: yes
  reboot:
  when: result_install_cgroups.changed
