- name: create_config_dir
  become: yes
  file: path=/etc/zookeeper/conf state=directory mode=755

- include: principal.yml
  vars: { kerberos_princ_username: zookeeper, kerberos_princ_keytab_path: /etc/zookeeper/conf/zookeeper.keytab, kerberos_princ_keytab_owner: zookeeper }
  when: kerberos_realm is defined

- name: copy_jaas_conf
  become: yes
  template: src=jaas.conf.j2 dest=/etc/zookeeper/conf/jaas.conf
  when: kerberos_realm is defined

- name: copy_config_files
  become: yes
  template: src={{ item }}.j2 dest=/etc/zookeeper/conf/{{ item }}
  with_items:
  - zoo.cfg
  - log4j.properties
  
- name: create_zookeeper_data_dir
  become: yes
  file: path={{ zookeeper_data_dir }} state=directory owner=zookeeper mode=755

- name: copy_myid_file
  become: yes
  template: src=myid.j2 dest={{zookeeper_data_dir}}/myid
 
- name: copy_zookeeper-env.sh
  become: yes
  template: src={{ item }}.j2 dest=/etc/zookeeper/conf/{{ item }}
  with_items:
  - zookeeper-env.sh

- name: create_zookeeper_log_dir
  become: yes
  file: path={{ zookeeper_log_dir }} state=directory owner=zookeeper mode=755

- name: prepare_systemd_service
  become: yes
  template:
    src: zookeeper-server.service.j2
    dest: /etc/systemd/system/zookeeper-server.service

- name: reload_systemd_service
  become: yes
  systemd:
    daemon_reload: yes

- name: prepare_pid_dir
  become: yes
  file:
    path: "{{ zookeeper_pid_dir }}"
    state: directory
    owner: zookeeper
