- name: create_datanode_data_dir
  become: yes
  file: path={{ item }} state=directory owner=hdfs group=hadoop mode=700
  with_items: "{{ dfs_datanode_data_dirs }}"

- name: prepare_systemd_service
  become: yes
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
  - hadoop-hdfs-datanode
  - hadoop-yarn-nodemanager

- name: reload_systemd_service
  become: yes
  systemd:
    daemon_reload: yes
  
- name: create_holder_directory_for_hadoop_tmp_dir
  become: yes
  file: path={{ hadoop_tmp_dir[0:hadoop_tmp_dir.rfind('/')] }} state=directory mode=755 owner=yarn group=yarn

- name: create_hdfs_pid_dir
  become: yes
  file: path={{ hdfs_pid_dir }} state=directory mode=755 owner=hdfs group=hdfs
  
- name: create_yarn_pid_dir
  become: yes
  file: path={{ yarn_pid_dir }} state=directory mode=755 owner=yarn group=yarn

- name: create_hdfs_log_dir
  become: yes
  file: path={{ hdfs_log_dir }} state=directory mode=755 owner=hdfs group=hadoop 
  
- name: create_yarn_log_dir
  become: yes
  file: path={{ yarn_log_dir }} state=directory mode=755 owner=yarn group=hadoop

- name: copy_defaults_file
  become: yes
  template: src=default_{{ item }}.j2 dest=/etc/default/{{ item }} mode=755 owner=root group=root
  with_items:
  - hadoop-hdfs-datanode
  - hadoop-yarn-nodemanager
