- name: create_hue_data_dir
  sudo: yes
  file: path={{ hue_data_dir }} state=directory owner=hue group=hadoop mode=755

- name: copy_hue_conf
  sudo: yes
  template: src={{ item }}.j2 dest=/etc/hue/conf/{{ item }} owner=root group=root mode=755
  with_items:
  - hue.ini
  - hue_httpd.conf
  - log.conf

- name: check_db_exists
  stat: path={{ hue_data_dir}}/desktop.db
  register: check_hue_db_stat

- name: sync_db_for_hue
  sudo: yes
  sudo_user: hue
  shell: /usr/lib/hue/build/env/bin/hue syncdb --noinput
  when: not check_hue_db_stat.stat.exists


