#!/bin/bash
#
# /etc/init.d/storm-drpc
#
# Startup script for storm-drpc
#
# chkconfig: 2345 20 80
# description: Starts and stops storm-drpc
. /etc/init.d/functions
stormBin=/usr/bin/storm
stormSvc=$(echo $0 | cut -d'-' -f2)
desc="Storm $stormSvc daemon"
outFile="/var/log/storm/$stormSvc.out"
ppidFile="/var/run/storm/$stormSvc.ppid"

if ! [ -f $stormBin ]; then
  echo "storm binary not found."
  exit 5
fi

if [ -f /etc/sysconfig/storm ]; then
  . /etc/sysconfig/storm
fi

start() {
  echo "Starting $desc (storm-$stormSvc): "

  if [ -f $ppidFile ] ; then
     ppid=$(cat $ppidFile)
     if [ -n "$ppid" ] ; then
        pgrep -f storm -P $ppid >/dev/null 2>&1
        if [ $? -eq 0 ] ; then
           echo "storm-$stormSvc is already running."
           exit 3
        fi
     fi
  fi

  su - $stormUser -c "nohup ${stormBin} $stormSvc >>$outFile 2>&1 & echo \$! >$ppidFile"
  RETVAL=$?
  return $RETVAL
}

stop() {
  echo "Shutting down $desc (storm-$stormSvc): "
  if [ ! -f $ppidFile ] ; then
     echo "storm-${stormSvc} ppid file $ppidFile not exist."
     exit 3
  fi
  ppid=$(cat $ppidFile)
  if [ -z "$ppid" ] ; then
     echo "storm-${stormSvc} ppid file $ppidFile is empty."
     exit 3
  fi
  pid=$(pgrep -f storm -P $ppid)
  if [ $? != 0 ] ; then
     echo "storm-$stormSvc is not running."
     exit 3
  fi

  pkill -f storm -P $ppid
  RETVAL=$?
  return $RETVAL
}

restart() {
    stop
    start
}

status() {
  if [ -f $ppidFile ] ; then
     ppid=$(cat $ppidFile)
     if [ -n "$ppid" ] ; then
        pid=$(pgrep -f storm -P $ppid)
     fi
  fi
  pid=$(pgrep -f storm -P $ppid)

  # TODO:check if storm is in the process of starting

  if [ -z $pid ]; then
    echo "storm-$stormSvc is NOT running."
    exit 3
  else
    echo "storm-$stormSvc is running (pid is $pid)."
  fi

}

case "$1" in
  start)   start;;
  stop)    stop;;
  restart) restart;;
  status)  status;;
  *)       echo "Usage: $0 {start|stop|restart}"
           RETVAL=2;;
esac
exit $RETVAL


