- name: check_jdk7_installed
  sudo: yes
  shell: rpm -qa|grep jdk-1.7.0_{{ jdk7_version }}-fcs.x86_64
  ignore_errors: yes
  changed_when: false
  failed_when: false
  always_run: true
  register: check_jdk7_installed

- name: download_oraclejdk7_by_wget
  shell: >
         wget --no-verbose --no-check-certificate --no-cookies {{ jdk7_downloadurl }}/jdk-7u{{ jdk7_version }}-linux-x64.rpm -O jdk-7u{{ jdk7_version }}-linux-x64.rpm chdir={{ jdk7_tmppath }} 
  when: check_jdk7_installed.rc != 0
  ignore_errors: True

- name: md5sum_rpm
  shell: md5sum {{ jdk7_tmppath }}/jdk-7u{{ jdk7_version }}-linux-x64.rpm
  when: check_jdk7_installed.rc != 0
  changed_when: false
  failed_when: false
  always_run: true
  register: md5sum_of_jdk

- name: check_md5sum
  fail: msg="md5sum does not match ... {{ md5sum_of_jdk.stdout }} should be {{ jdk7_md5sum }}"
  when: check_jdk7_installed.rc != 0 and md5sum_of_jdk.stdout.find('{{ jdk7_md5sum }}')

- name: install_oraclejdk
  sudo: yes
  yum: name={{ jdk7_tmppath }}/jdk-7u{{ jdk7_version }}-linux-x64.rpm state=installed
  when: check_jdk7_installed.rc != 0
