- name: check keytab
  become: yes
  stat: path={{ kerberos_princ_dest_keytab }}
  register: kerberos_princ_dest_keytab_stat

- name: prepare_script
  become: yes
  template: src=merge-keytabs.ktutil.j2 dest=/root/merge-keytabs.ktutil
  when: kerberos_princ_dest_keytab_stat.stat.exists == False

- name: run_script
  become: yes
  shell: ktutil </root/merge-keytabs.ktutil
  when: kerberos_princ_dest_keytab_stat.stat.exists == False
  notify: "Modify keytab permissions for {{ kerberos_princ_keytab_owner }}"
