- name: check_exists_hfds_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -ls {{ tez_hdfs_dir }}
  register: check_exists_hdfs_dir
  changed_when: false
  failed_when: false
  check_mode: no

- name: create_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -mkdir -p {{ tez_hdfs_dir }}
  when: check_exists_hdfs_dir.rc != 0

- name: change_owner_and_group_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chown -R hdfs:hadoop {{ tez_hdfs_dir }}
  when: check_exists_hdfs_dir.rc != 0

- name: change_mode_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chmod -R 555 {{ tez_hdfs_dir }}
  when: check_exists_hdfs_dir.rc != 0
