- name: set_SPARK_HOME
  become: yes
  template: src=spark.sh.j2 dest=/etc/profile.d/spark.sh owner=root group=root mode=644

- name: set_environment
  become: yes
  template: src=spark.conf.j2 dest=/etc/environment.d/50-spark.conf owner=root group=root mode=644

- name: create_spark_conf_dir
  become: yes
  file: path=/etc/spark/conf/ state=directory owner=root group=root mode=755

- include: principal.yml
  vars: { kerberos_princ_username: spark, kerberos_princ_keytab_path: /etc/spark/conf/spark.keytab, kerberos_princ_keytab_owner: spark }
  when: kerberos_realm is defined

- name: copy_spark_conf_files
  become: yes
  template: src={{ item }}.j2 dest=/etc/spark/conf/{{ item }} owner=root group=root mode=755
  with_items:
  - spark-defaults.conf
  - spark-env.sh
  - metrics.properties
  - log4j.properties
  - fairscheduler.xml

- name: copy_sudoers_conf_of_SPARK_HOME
  become: yes
  copy: src=env_keep_sparkhome dest=/etc/sudoers.d/ owner=root mode=440   
