- name: check_exists_hfds_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -ls {{ item.path }}
  register: check_exists_hdfs_dir
  changed_when: false
  failed_when: false
  always_run: true
  with_items:
    - {path: '/var', mode: '1777', owner: 'hdfs', group: 'hadoop'}
    - {path: '/var/log', mode: '1777', owner: 'hdfs', group: 'hadoop'}
    - {path: '/mapred', mode: '755', owner: 'mapred', group: 'hadoop'}
    - {path: '/mapred/staging', mode: '1777', owner: 'mapred', group: 'hadoop'}
    - {path: '/mapred/system', mode: '700', owner: 'mapred', group: 'hadoop'}
    - {path: '/tmp/hadoop-yarn', mode: '1777', owner: 'yarn', group: 'hadoop'}
    - {path: '/tmp/hadoop-yarn/staging', mode: '1777', owner: 'mapred', group: 'hadoop'}
    
- name: create_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -mkdir -p {{ item.item.path }}
  when: item.rc != 0
  with_items: "{{ check_exists_hdfs_dir.results }}"
  
- name: change_owner_and_group_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chown -R {{ item.item.owner }}:{{ item.item.group }} {{ item.item.path }}
  when: item.rc != 0
  with_items: "{{ check_exists_hdfs_dir.results }}"

- name: change_mode_of_hdfs_dir
  become: yes
  become_user: hdfs
  shell: hdfs dfs -chmod -R {{ item.item.mode }} {{ item.item.path }}
  when: item.rc != 0
  with_items: "{{ check_exists_hdfs_dir.results }}"

