- name: create_spark_log_dir
  become: yes
  file: path={{ spark_log_dir }} state=directory owner=spark group=hadoop mode=755

- name: remove_spark_log_dir
  become: yes
  file: path=/usr/hdp/{{ hdp_version }}/spark2/logs state=absent

- name: create_symbolic_link_to_spark_log_dir
  become: yes
  file: path=/usr/hdp/{{ hdp_version }}/spark2/logs state=link src={{ spark_log_dir }}
  register: md5sum_spark

- name: create_spark_pid_dir
  become: yes
  file: path={{ spark_pid_dir }} state=directory owner=spark group=spark mode=775
