- name: set_local_port_range
  become: yes
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_local_port_range = {{ ipv4_ip_local_port_range_min }} {{ ipv4_ip_local_port_range_max }}" regexp="net.ipv4.ip_local_port_range"
    
- name: set_somaxconn
  become: yes
  lineinfile: dest=/etc/sysctl.conf line="net.core.somaxconn = {{ net_core_somaxconn }}" regexp="net.core.somaxconn"
