- name: set_transparent_hugepage
  become: yes
  lineinfile: dest=/etc/rc.local line="echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag" regexp="echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag"
