---

- name: Dump all vars
  template: src=dumpall.j2 dest={{ dumpall_guest_destination }}

- name: Retrieve dumpfile
  fetch: "src=/tmp/ansible.all dest={{ dumpall_host_destination }} flat={{ dumpall_flat_mode }}"
  when: "dumpall_host_destination is defined"

- name: Remove dumpfile on the guest
  file: path={{ dumpall_guest_destination }} state=absent
  when: "dumpall_host_destination is defined"
