- name: Install git
  yum: name=git state=latest
  become: yes
  
- name: Clone repository
  git: repo=https://github.com/apache/tez.git dest={{ swimlane_install_path }}/apache-tez-{{ swimlane_tez_version }}-src version=release-{{ swimlane_tez_version }}
  become: yes

- name: install_httpd
  yum: name=httpd state=installed
  become: yes

