- name: create_journalnode_data_dir
  become: yes
  file: path={{ dfs_journalnode_edits_dir }} state=directory owner=hdfs group=hadoop mode=700

- name: prepare_systemd_service
  become: yes
  template:
    src: hadoop-hdfs-journalnode.service.j2
    dest: /etc/systemd/system/hadoop-hdfs-journalnode.service

- name: reload_systemd_service
  become: yes
  systemd:
    daemon_reload: yes

- name: prepare_pid_dir
  become: yes
  file:
    path: "{{ hdfs_pid_dir }}"
    state: directory
    owner: hdfs
  
- name: create_hdfs_log_dir
  become: yes
  file: path={{ hdfs_log_dir }} state=directory mode=755 owner=hdfs group=hadoop 

- name: copy_journalnode_defaults_file
  become: yes
  template: src=default_{{ item }}.j2 dest=/etc/default/{{ item }} mode=755 owner=hdfs group=hdfs
  with_items:
  - hadoop-hdfs-journalnode

