- name: Modify keytab permissions for hdfs
  file: path=/etc/hadoop/conf/hdfs.keytab owner=hdfs group=hadoop mode=0400
  become: yes
  notify: Modify http keytab permissions

- name: Modify http keytab permissions
  become: yes
  file: path=/etc/hadoop/conf/http.keytab owner=hdfs group=hadoop mode=0400

- name: Modify keytab permissions for mapred
  become: yes
  file: path=/etc/hadoop/conf/mapred.keytab owner=mapred group=hadoop mode=0400

- name: Modify keytab permissions for yarn
  become: yes
  file: path=/etc/hadoop/conf/yarn.keytab owner=yarn group=hadoop mode=0400

