- hosts: hadoop_swimlane
  tasks:
    - name: start_httpd
      become: yes
      service: name=httpd state=started

    - name: delete_swimlane_old_output
      become: yes
      file: path={{ item }}/{{ yarn_application_id }}.svg state=absent
      with_items:
      - "{{ swimlane_httpd_path}}/{{ swimlane_httpd_prefix }}"
      - "{{ swimlane_install_path }}/apache-tez-{{ swimlane_tez_version }}-src/tez-tools/swimlanes"
  
    - name: create_swimlane_analyze
      shell: bash yarn-swimlanes.sh {{ yarn_application_id }}
      args:
        chdir: "{{ swimlane_install_path }}/apache-tez-{{ swimlane_tez_version }}-src/tez-tools/swimlanes/"
  
    - name: move_to_httpd_path
      become: yes
      shell: mv {{ swimlane_install_path }}/apache-tez-{{ swimlane_tez_version }}-src/tez-tools/swimlanes/{{ yarn_application_id }}.svg {{ swimlane_httpd_path }}/{{ swimlane_httpd_prefix }}
    
    - name: show_http_url
      become: yes
      debug: msg=http://{{ inventory_hostname }}/{{ swimlane_httpd_prefix }}/{{ yarn_application_id }}.svg
